In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/occupancy.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/distance.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/acndata_sessions.json.xlsx
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/adj.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/stations.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/information.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/volume.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/time.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/duration.csv
/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/price.csv

In [2]:

df = pd.read_excel("/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/acndata_sessions.json.xlsx")

#

In [3]:
df.to_csv("output.csv", index=False)

print(df.head())

   _meta  end  min_kWh     site  start  _items                       _id  \
0    NaN  NaN      NaN  caltech    NaN     NaN  5bc90cb9f9af8b0d7fe77cd2
1    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd3
2    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd4
3    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd5
4    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd6

   clusterID                 connectionTime                 disconnectTime  \
0       39.0  Wed, 25 Apr 2018 11:08:04 GMT  Wed, 25 Apr 2018 13:20:10 GMT
1       39.0  Wed, 25 Apr 2018 13:45:10 GMT  Thu, 26 Apr 2018 00:56:16 GMT
2       39.0  Wed, 25 Apr 2018 13:45:50 GMT  Wed, 25 Apr 2018 23:04:45 GMT
3       39.0  Wed, 25 Apr 2018 14:37:06 GMT  Wed, 25 Apr 2018 23:55:34 GMT
4       39.0  Wed, 25 Apr 2018 14:40:34 GMT  Wed, 25 Apr 2018 23:03:12 GMT

   ... userID  userInputs WhPerMile  kWhRequested milesRequested  \
0  ...    NaN         NaN       NaN           NaN            NaN
1  ...    NaN         NaN       NaN           NaN            NaN
2  ...    NaN         NaN       NaN           NaN            NaN
3  ...    NaN         NaN       NaN           NaN            NaN
4  ...    NaN         NaN       NaN           NaN            NaN

  minutesAvailable modifiedAt  paymentRequired  requestedDeparture  userID.1
0              NaN        NaN              NaN                 NaN       NaN
1              NaN        NaN              NaN                 NaN       NaN
2              NaN        NaN              NaN                 NaN       NaN
3              NaN        NaN              NaN                 NaN       NaN
4              NaN        NaN              NaN                 NaN       NaN

[5 rows x 27 columns]

In [4]:
df.head()

,_meta,end,min_kWh,site,start,_items,_id,clusterID,connectionTime,disconnectTime,...,userID,userInputs,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture,userID.1
0,NaN,NaN,NaN,caltech,NaN,NaN,5bc90cb9f9af8b0d7fe77cd2,39.0,"Wed, 25 Apr 2018 11:08:04 GMT","Wed, 25 Apr 2018 13:20:10 GMT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd3,39.0,"Wed, 25 Apr 2018 13:45:10 GMT","Thu, 26 Apr 2018 00:56:16 GMT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd4,39.0,"Wed, 25 Apr 2018 13:45:50 GMT","Wed, 25 Apr 2018 23:04:45 GMT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd5,39.0,"Wed, 25 Apr 2018 14:37:06 GMT","Wed, 25 Apr 2018 23:55:34 GMT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd6,39.0,"Wed, 25 Apr 2018 14:40:34 GMT","Wed, 25 Apr 2018 23:03:12 GMT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['_meta', 'end', 'min_kWh', 'site', 'start', '_items', '_id',
       'clusterID', 'connectionTime', 'disconnectTime', 'doneChargingTime',
       'kWhDelivered', 'sessionID', 'siteID', 'spaceID', 'stationID',
       'timezone', 'userID', 'userInputs', 'WhPerMile', 'kWhRequested',
       'milesRequested', 'minutesAvailable', 'modifiedAt', 'paymentRequired',
       'requestedDeparture', 'userID.1'],
      dtype='object')

In [6]:
l=df.columns.tolist()
#print(l)
for col in l:
     print(f'{col}, : null value->{df[col].isna().sum()}')

_meta, : null value->16304
end, : null value->16304
min_kWh, : null value->16304
site, : null value->16303
start, : null value->16304
_items, : null value->16304
_id, : null value->1305
clusterID, : null value->1305
connectionTime, : null value->1305
disconnectTime, : null value->1305
doneChargingTime, : null value->1313
kWhDelivered, : null value->1305
sessionID, : null value->1305
siteID, : null value->1305
spaceID, : null value->1305
stationID, : null value->1305
timezone, : null value->1305
userID, : null value->14072
userInputs, : null value->16304
WhPerMile, : null value->12767
kWhRequested, : null value->12767
milesRequested, : null value->12767
minutesAvailable, : null value->12767
modifiedAt, : null value->12767
paymentRequired, : null value->12767
requestedDeparture, : null value->12767
userID.1, : null value->12767

In [7]:

df['connectionTime'] = pd.to_datetime(df['connectionTime'], utc=True)

print("Min date:", df['connectionTime'].min())
print("Max date:", df['connectionTime'].max())

Min date: 2018-04-25 11:08:04+00:00
Max date: 2018-12-16 03:01:46+00:00

In [8]:
df.shape

(16304, 27)

In [9]:
df1=pd.read_csv('/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/adj.csv')
df1.head()

,node_id,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,102,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,105,0,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,107,0,1,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,108,0,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,109,0,0,0,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0

# Start ->

In [10]:
# =========================
# Imports
# =========================

import json
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
from datetime import datetime
import pytz
import matplotlib.pyplot as plt
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries loaded successfully")

Libraries loaded successfully

In [11]:
acn_path='/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds/acndata_sessions.json.xlsx'
urban_path='/kaggle/input/datasets/sahilhussain2410/ev-vehicles-data/ds'

In [12]:
acn = pd.read_excel(acn_path)

print(acn.shape)
display(acn.head())

print(acn.columns.tolist())

(16304, 27)

,_meta,end,min_kWh,site,start,_items,_id,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture,userID.1
0,NaN,NaN,NaN,caltech,NaN,NaN,5bc90cb9f9af8b0d7fe77cd2,39.0,"Wed, 25 Apr 2018 11:08:04 GMT","Wed, 25 Apr 2018 13:20:10 GMT","Wed, 25 Apr 2018 13:21:10 GMT",7.932,2_39_78_362_2018-04-25 11:08:04.400812,2.0,CA-496,2-39-78-362,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd3,39.0,"Wed, 25 Apr 2018 13:45:10 GMT","Thu, 26 Apr 2018 00:56:16 GMT","Wed, 25 Apr 2018 16:44:15 GMT",10.013,2_39_95_27_2018-04-25 13:45:09.617470,2.0,CA-319,2-39-95-27,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd4,39.0,"Wed, 25 Apr 2018 13:45:50 GMT","Wed, 25 Apr 2018 23:04:45 GMT","Wed, 25 Apr 2018 14:51:44 GMT",5.257,2_39_79_380_2018-04-25 13:45:49.962001,2.0,CA-489,2-39-79-380,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd5,39.0,"Wed, 25 Apr 2018 14:37:06 GMT","Wed, 25 Apr 2018 23:55:34 GMT","Wed, 25 Apr 2018 16:05:22 GMT",5.177,2_39_79_379_2018-04-25 14:37:06.460772,2.0,CA-327,2-39-79-379,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,5bc90cb9f9af8b0d7fe77cd6,39.0,"Wed, 25 Apr 2018 14:40:34 GMT","Wed, 25 Apr 2018 23:03:12 GMT","Wed, 25 Apr 2018 17:40:30 GMT",10.119,2_39_79_381_2018-04-25 14:40:33.638896,2.0,CA-490,2-39-79-381,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['_meta', 'end', 'min_kWh', 'site', 'start', '_items', '_id', 'clusterID', 'connectionTime', 'disconnectTime', 'doneChargingTime', 'kWhDelivered', 'sessionID', 'siteID', 'spaceID', 'stationID', 'timezone', 'userID', 'userInputs', 'WhPerMile', 'kWhRequested', 'milesRequested', 'minutesAvailable', 'modifiedAt', 'paymentRequired', 'requestedDeparture', 'userID.1']

In [13]:
information = pd.read_csv(
    urban_path + "/information.csv"
)

stations = pd.read_csv(
    urban_path + "/stations.csv"
)

time_df = pd.read_csv(
    urban_path + "/time.csv"
)

volume = pd.read_csv(
    urban_path + "/volume.csv"
)

occupancy = pd.read_csv(
    urban_path + "/occupancy.csv"
)

price = pd.read_csv(
    urban_path + "/price.csv"
)

duration = pd.read_csv(
    urban_path + "/duration.csv"
)

distance = pd.read_csv(
    urban_path + "/distance.csv"
)

adj = pd.read_csv(
    urban_path + "/adj.csv"
)

In [14]:
for name, df in {
    "information": information,
    "stations": stations,
    "time": time_df,
    "volume": volume,
    "occupancy": occupancy,
    "price": price,
    "duration": duration,
    "distance": distance,
    "adj": adj
}.items():

    print("=" * 50)
    print(name)
    print(df.shape)

==================================================
information
(247, 10)
==================================================
stations
(1706, 6)
==================================================
time
(8640, 6)
==================================================
volume
(8640, 248)
==================================================
occupancy
(8640, 248)
==================================================
price
(8640, 248)
==================================================
duration
(8640, 248)
==================================================
distance
(247, 248)
==================================================
adj
(247, 248)

In [15]:
# created timestamp from time_df 
time_df["timestamp"] = pd.to_datetime(
    dict(
        year=time_df["year"],
        month=time_df["month"],
        day=time_df["day"],
        hour=time_df["hour"],
        minute=time_df["minute"],
        second=time_df["second"]
    )
)
print(time_df["timestamp"].min())
print(time_df["timestamp"].max())
time_df.head()

2022-06-19 00:00:00
2022-07-18 23:55:00

   month  day  year  hour  minute  second           timestamp
0      6   19  2022     0       0       0 2022-06-19 00:00:00
1      6   19  2022     0       5       0 2022-06-19 00:05:00
2      6   19  2022     0      10       0 2022-06-19 00:10:00
3      6   19  2022     0      15       0 2022-06-19 00:15:00
4      6   19  2022     0      20       0 2022-06-19 00:20:00

In [16]:
volume.head()
time_df.head()

   month  day  year  hour  minute  second           timestamp
0      6   19  2022     0       0       0 2022-06-19 00:00:00
1      6   19  2022     0       5       0 2022-06-19 00:05:00
2      6   19  2022     0      10       0 2022-06-19 00:10:00
3      6   19  2022     0      15       0 2022-06-19 00:15:00
4      6   19  2022     0      20       0 2022-06-19 00:20:00

In [17]:
# creating timestamp for each file
volume["timestamp"] = time_df["timestamp"]
occupancy["timestamp"] = time_df["timestamp"]
price["timestamp"] = time_df["timestamp"]
duration["timestamp"] = time_df["timestamp"]

# ACN preprocessing

In [18]:
#ACN missing values report
missing_report = pd.DataFrame({
    "missing_count": acn.isna().sum(),
    "missing_pct": (
        acn.isna().mean() * 100
    ).round(2)
})

missing_report = (
    missing_report
    .sort_values(
        "missing_pct",
        ascending=False
    )
)

print(missing_report.head(30))

                    missing_count  missing_pct
_meta                       16304       100.00
end                         16304       100.00
min_kWh                     16304       100.00
start                       16304       100.00
_items                      16304       100.00
userInputs                  16304       100.00
site                        16303        99.99
userID                      14072        86.31
paymentRequired             12767        78.31
modifiedAt                  12767        78.31
minutesAvailable            12767        78.31
requestedDeparture          12767        78.31
userID.1                    12767        78.31
kWhRequested                12767        78.31
WhPerMile                   12767        78.31
milesRequested              12767        78.31
doneChargingTime             1313         8.05
clusterID                    1305         8.00
_id                          1305         8.00
disconnectTime               1305         8.00
connectionTime               1305         8.00
stationID                    1305         8.00
timezone                     1305         8.00
sessionID                    1305         8.00
kWhDelivered                 1305         8.00
siteID                       1305         8.00
spaceID                      1305         8.00

In [19]:
# ACN duplicate  rows
print(
    "Duplicate rows:",
    acn.duplicated().sum()
)

Duplicate rows: 22

In [20]:
# ACN duplicate session IDs
print(
    "Duplicate session IDs:",
    acn["sessionID"].duplicated().sum()
)

Duplicate session IDs: 1304

In [21]:
acn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16304 entries, 0 to 16303
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _meta               0 non-null      float64
 1   end                 0 non-null      float64
 2   min_kWh             0 non-null      float64
 3   site                1 non-null      object
 4   start               0 non-null      float64
 5   _items              0 non-null      float64
 6   _id                 14999 non-null  object
 7   clusterID           14999 non-null  float64
 8   connectionTime      14999 non-null  object
 9   disconnectTime      14999 non-null  object
 10  doneChargingTime    14991 non-null  object
 11  kWhDelivered        14999 non-null  float64
 12  sessionID           14999 non-null  object
 13  siteID              14999 non-null  float64
 14  spaceID             14999 non-null  object
 15  stationID           14999 non-null  object
 16  timezone            14999 non-null  object
 17  userID              2232 non-null   float64
 18  userInputs          0 non-null      float64
 19  WhPerMile           3537 non-null   float64
 20  kWhRequested        3537 non-null   float64
 21  milesRequested      3537 non-null   float64
 22  minutesAvailable    3537 non-null   float64
 23  modifiedAt          3537 non-null   object
 24  paymentRequired     3537 non-null   object
 25  requestedDeparture  3537 non-null   object
 26  userID.1            3537 non-null   float64
dtypes: float64(15), object(12)
memory usage: 3.4+ MB

In [22]:
acn["sessionID"].nunique(dropna=True)

14999

In [23]:
acn["sessionID"].isna().sum()

np.int64(1305)

## ACN Cleaning

In [24]:
drop_cols = [
    "_meta",
    "end",
    "min_kWh",
    "start",
    "_items",
    "userInputs"
]
acn = acn.drop(columns=drop_cols)

In [25]:
# removing duplicate rows
acn = acn[
    acn["sessionID"].notna()
].copy()
print(acn.shape)

(14999, 21)

In [26]:
# converting time columns
time_cols = [
    "connectionTime",
    "disconnectTime",
    "doneChargingTime",
    "modifiedAt",
    "requestedDeparture"
]

for col in time_cols:
    
    if col in acn.columns:
        
        acn[col] = pd.to_datetime(
            acn[col],
            errors="coerce"
        )

In [27]:
acn[time_cols].dtypes

connectionTime        datetime64[ns]
disconnectTime        datetime64[ns]
doneChargingTime      datetime64[ns]
modifiedAt            datetime64[ns]
requestedDeparture    datetime64[ns]
dtype: object

In [28]:
acn["connectionTime"].head()
acn['connectionTime'].iloc[0]

Timestamp('2018-04-25 11:08:04')

In [29]:
acn["connected_hours"] = (
    acn["disconnectTime"]
    - acn["connectionTime"]
).dt.total_seconds() / 3600
acn[['connectionTime','disconnectTime','connected_hours']].head()

       connectionTime      disconnectTime  connected_hours
0 2018-04-25 11:08:04 2018-04-25 13:20:10         2.201667
1 2018-04-25 13:45:10 2018-04-26 00:56:16        11.185000
2 2018-04-25 13:45:50 2018-04-25 23:04:45         9.315278
3 2018-04-25 14:37:06 2018-04-25 23:55:34         9.307778
4 2018-04-25 14:40:34 2018-04-25 23:03:12         8.377222

In [30]:
print(acn['doneChargingTime'].isna().sum())
acn["doneChargingTime"] = acn["doneChargingTime"].fillna(acn["disconnectTime"])

8

In [31]:
acn["charging_hours"] = (
    acn["doneChargingTime"]
    - acn["connectionTime"]
).dt.total_seconds() / 3600

acn[['doneChargingTime','connectionTime','charging_hours']].head()

     doneChargingTime      connectionTime  charging_hours
0 2018-04-25 13:21:10 2018-04-25 11:08:04        2.218333
1 2018-04-25 16:44:15 2018-04-25 13:45:10        2.984722
2 2018-04-25 14:51:44 2018-04-25 13:45:50        1.098333
3 2018-04-25 16:05:22 2018-04-25 14:37:06        1.471111
4 2018-04-25 17:40:30 2018-04-25 14:40:34        2.998889

In [32]:
acn['charging_hours'].isna().sum()

np.int64(0)

In [33]:
# sanity check
acn[
    [
        "connected_hours",
        "charging_hours"
    ]
].describe()

       connected_hours  charging_hours
count     14999.000000    14999.000000
mean          5.923631        3.235367
std           6.459457        3.184829
min           0.087500       -0.689444
25%           2.025139        1.270278
50%           4.764167        2.240556
75%           8.729722        4.243889
max         245.269167      104.428333

In [34]:
print(
    (acn["connected_hours"] < 0).sum()
)

print(
    (acn["charging_hours"] < 0).sum()
)

0
18

In [35]:
# acn.loc[acn['charging_hours']<0,['doneChargingTime','connectionTime','disconnectTime','charging_hours','connected_hours']].head(18)

In [36]:
print(acn['kWhDelivered'].isna().sum())
print(acn['charging_hours'].isna().sum())
acn[acn['charging_hours']==0]

0
0

,site,_id,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture,userID.1,connected_hours,charging_hours
607,NaN,5bc917d0f9af8b0dc677b8d1,39.0,2018-05-07 20:47:49,2018-05-08 01:32:46,2018-05-07 20:47:49,3.870,2_39_89_439_2018-05-07 20:47:49.332393,2.0,CA-501,2-39-89-439,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,4.749167,0.0
616,NaN,5bc917d0f9af8b0dc677b8da,39.0,2018-05-07 20:47:55,2018-05-08 03:02:19,2018-05-07 20:47:55,2.628,2_39_90_26_2018-05-07 20:47:55.140558,2.0,CA-316,2-39-90-26,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,6.240000,0.0

In [37]:
acn["avg_power_kw"] = (
    acn["kWhDelivered"]
    / acn["charging_hours"]
)
acn[['avg_power_kw','kWhDelivered','charging_hours']].head()

   avg_power_kw  kWhDelivered  charging_hours
0      3.575657         7.932        2.218333
1      3.354751        10.013        2.984722
2      4.786343         5.257        1.098333
3      3.519109         5.177        1.471111
4      3.374250        10.119        2.998889

In [38]:
acn["avg_power_kw"].describe()

count    1.499900e+04
mean              inf
std               NaN
min     -5.388120e+04
25%      2.022757e+00
50%      3.098734e+00
75%      5.402313e+00
max               inf
Name: avg_power_kw, dtype: float64

In [39]:
# for station
print(
    acn["stationID"].nunique()
)
acn["stationID"].value_counts().tail()

54

stationID
2-39-129-563    82
2-39-125-559    68
2-39-83-387     64
2-39-82-384     10
2-39-82-385      4
Name: count, dtype: int64

In [40]:
# create hour and check
acn["hour"] = (
    acn["connectionTime"]
    .dt.floor("H")
)
acn[
    [
        "connectionTime",
        "hour"
    ]
].head()

       connectionTime                hour
0 2018-04-25 11:08:04 2018-04-25 11:00:00
1 2018-04-25 13:45:10 2018-04-25 13:00:00
2 2018-04-25 13:45:50 2018-04-25 13:00:00
3 2018-04-25 14:37:06 2018-04-25 14:00:00
4 2018-04-25 14:40:34 2018-04-25 14:00:00

In [41]:
## removing negative charging hours and zero charging hours
acn = acn[
    acn["charging_hours"] > 0
].copy()

In [42]:
acn["avg_power_kw"] = (
    acn["kWhDelivered"]
    / acn["charging_hours"]
)
acn['avg_power_kw'].describe()

count    14979.000000
mean         3.638293
std          9.041431
min          0.014163
25%          2.024644
50%          3.100104
75%          5.403871
max       1033.012289
Name: avg_power_kw, dtype: float64

In [43]:
acn.describe()

,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,siteID,userID,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,requestedDeparture,userID.1,connected_hours,charging_hours,avg_power_kw,hour
count,14979.0,14979,14979,14979,14979.000000,14979.0,2231.000000,2231.000000,2231.000000,2231.000000,2231.000000,2231,13,2231.000000,14979.000000,14979.000000,14979.000000,14979
mean,39.0,2018-08-19 05:54:08.889111552,2018-08-19 11:49:18.601842432,2018-08-19 09:08:32.266106112,9.010819,2.0,629.131779,344.508292,22.090338,69.457194,328.563873,2018-11-05 22:38:03.093680128,2018-05-17 05:48:01,629.131779,5.919365,3.239827,3.638293,2018-08-19 05:24:03.220508672
min,39.0,2018-04-25 11:08:04,2018-04-25 13:20:10,2018-04-25 13:21:10,0.501000,2.0,1.000000,200.000000,2.250000,10.000000,1.000000,2018-04-30 15:08:54,2018-05-01 00:17:49,1.000000,0.087500,0.001944,0.014163,2018-04-25 11:00:00
25%,39.0,2018-06-28 16:04:10.500000,2018-06-28 23:38:47,2018-06-28 19:32:55.500000,4.018000,2.0,300.000000,250.000000,9.390000,30.000000,157.000000,2018-10-20 03:48:59.500000,2018-05-14 14:50:26,300.000000,2.024583,1.274583,2.024644,2018-06-28 16:00:00
50%,39.0,2018-08-21 16:23:37,2018-08-22 00:50:32,2018-08-21 22:16:32,7.447000,2.0,567.000000,333.000000,17.500000,50.000000,307.000000,2018-11-13 00:28:55,2018-05-16 19:24:08,567.000000,4.761667,2.245000,3.100104,2018-08-21 16:00:00
75%,39.0,2018-10-07 23:48:22.500000,2018-10-08 03:11:06,2018-10-08 01:56:33.500000,13.204000,2.0,945.000000,400.000000,27.000000,90.000000,502.000000,2018-11-29 17:04:20,2018-05-23 00:25:09,945.000000,8.730139,4.245556,5.403871,2018-10-07 23:00:00
max,39.0,2018-12-16 03:01:46,2018-12-16 20:54:29,2018-12-16 08:29:42,69.373000,2.0,1509.000000,600.000000,150.000000,300.000000,1078.000000,2018-12-16 03:01:49,2018-05-25 15:01:17,1509.000000,245.269167,104.428333,1033.012289,2018-12-16 03:00:00
std,0.0,NaN,NaN,NaN,7.055499,0.0,370.234366,100.559769,17.924463,58.633855,192.185361,NaN,NaN,370.234366,6.439673,3.184603,9.041431,NaN

In [44]:
acn.isna().sum()

site                  14978
_id                       0
clusterID                 0
connectionTime            0
disconnectTime            0
doneChargingTime          0
kWhDelivered              0
sessionID                 0
siteID                    0
spaceID                   0
stationID                 0
timezone                  0
userID                12748
WhPerMile             12748
kWhRequested          12748
milesRequested        12748
minutesAvailable      12748
modifiedAt            12748
paymentRequired       12748
requestedDeparture    14966
userID.1              12748
connected_hours           0
charging_hours            0
avg_power_kw              0
hour                      0
dtype: int64

In [45]:
display(acn.head())
acn['site'].unique()

,site,_id,clusterID,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,WhPerMile,kWhRequested,milesRequested,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture,userID.1,connected_hours,charging_hours,avg_power_kw,hour
0,caltech,5bc90cb9f9af8b0d7fe77cd2,39.0,2018-04-25 11:08:04,2018-04-25 13:20:10,2018-04-25 13:21:10,7.932,2_39_78_362_2018-04-25 11:08:04.400812,2.0,CA-496,2-39-78-362,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,2.201667,2.218333,3.575657,2018-04-25 11:00:00
1,NaN,5bc90cb9f9af8b0d7fe77cd3,39.0,2018-04-25 13:45:10,2018-04-26 00:56:16,2018-04-25 16:44:15,10.013,2_39_95_27_2018-04-25 13:45:09.617470,2.0,CA-319,2-39-95-27,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,11.185000,2.984722,3.354751,2018-04-25 13:00:00
2,NaN,5bc90cb9f9af8b0d7fe77cd4,39.0,2018-04-25 13:45:50,2018-04-25 23:04:45,2018-04-25 14:51:44,5.257,2_39_79_380_2018-04-25 13:45:49.962001,2.0,CA-489,2-39-79-380,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,9.315278,1.098333,4.786343,2018-04-25 13:00:00
3,NaN,5bc90cb9f9af8b0d7fe77cd5,39.0,2018-04-25 14:37:06,2018-04-25 23:55:34,2018-04-25 16:05:22,5.177,2_39_79_379_2018-04-25 14:37:06.460772,2.0,CA-327,2-39-79-379,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,9.307778,1.471111,3.519109,2018-04-25 14:00:00
4,NaN,5bc90cb9f9af8b0d7fe77cd6,39.0,2018-04-25 14:40:34,2018-04-25 23:03:12,2018-04-25 17:40:30,10.119,2_39_79_381_2018-04-25 14:40:33.638896,2.0,CA-490,2-39-79-381,America/Los_Angeles,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaT,NaN,8.377222,2.998889,3.374250,2018-04-25 14:00:00

array(['caltech', nan], dtype=object)

## making ACN valuable

In [46]:
acn_hourly = (
    acn
    .groupby(
        [
            "stationID",
            "hour"
        ]
    )
    .agg(
        demand_kwh=(
            "kWhDelivered",
            "sum"
        ),
        
        num_sessions=(
            "sessionID",
            "count"
        ),
        
        avg_session_kwh=(
            "kWhDelivered",
            "mean"
        ),
        
        avg_connected_hours=(
            "connected_hours",
            "mean"
        ),
        
        avg_charging_hours=(
            "charging_hours",
            "mean"
        )
    )
    .reset_index()
)

In [47]:
print(acn_hourly.shape)
acn_hourly.head()

(14871, 7)

,stationID,hour,demand_kwh,num_sessions,avg_session_kwh,avg_connected_hours,avg_charging_hours
0,2-39-123-23,2018-04-25 16:00:00,14.693,1,14.693,8.527778,8.213889
1,2-39-123-23,2018-04-26 02:00:00,13.892,1,13.892,2.208056,2.206667
2,2-39-123-23,2018-04-26 16:00:00,10.248,1,10.248,3.304722,3.303333
3,2-39-123-23,2018-04-27 16:00:00,6.444,1,6.444,2.913889,2.912778
4,2-39-123-23,2018-04-28 15:00:00,5.275,1,5.275,1.569722,1.567500

In [48]:
#revenue
BASE_PRICE = 15
acn_hourly["price"] = BASE_PRICE
acn_hourly["revenue"] = (
    acn_hourly["demand_kwh"]
    * acn_hourly["price"]
)

In [49]:
#station stats (capactiy)
station_stats = (
    acn
    .groupby("stationID")
    .agg(
        total_sessions=(
            "sessionID",
            "count"
        )
    )
)

## Temporal Feature Engineering

In [50]:
acn_hourly["hour_of_day"] = (
    acn_hourly["hour"]
    .dt.hour
)
acn_hourly["day_of_week"] = (
    acn_hourly["hour"]
    .dt.dayofweek
)
acn_hourly["is_weekend"] = (
    acn_hourly["day_of_week"]
    >= 5
).astype(int)
acn_hourly["month"] = (
    acn_hourly["hour"]
    .dt.month
)

In [51]:

print(
    acn_hourly["hour"].min()
)

print(
    acn_hourly["hour"].max()
)
acn_hourly.head()
acn_hourly.columns

2018-04-25 11:00:00
2018-12-16 03:00:00

Index(['stationID', 'hour', 'demand_kwh', 'num_sessions', 'avg_session_kwh',
       'avg_connected_hours', 'avg_charging_hours', 'price', 'revenue',
       'hour_of_day', 'day_of_week', 'is_weekend', 'month'],
      dtype='object')

In [52]:
keep_cols = [
    "sessionID",
    "stationID",
    "connectionTime",
    "disconnectTime",
    "doneChargingTime",
    "kWhDelivered",
    "siteID",
    "clusterID"
]
acn.columns

Index(['site', '_id', 'clusterID', 'connectionTime', 'disconnectTime',
       'doneChargingTime', 'kWhDelivered', 'sessionID', 'siteID', 'spaceID',
       'stationID', 'timezone', 'userID', 'WhPerMile', 'kWhRequested',
       'milesRequested', 'minutesAvailable', 'modifiedAt', 'paymentRequired',
       'requestedDeparture', 'userID.1', 'connected_hours', 'charging_hours',
       'avg_power_kw', 'hour'],
      dtype='object')

In [53]:
all_hours = pd.date_range(
    start=acn_hourly["hour"].min(),
    end=acn_hourly["hour"].max(),
    freq="H"
)
len(all_hours)

5633

In [54]:
all_stations = (
    acn_hourly["stationID"]
    .unique()
)
len(all_stations)

54

In [55]:
# full grid of hour*stations
full_grid = pd.MultiIndex.from_product(
    [
        all_stations,
        all_hours
    ],
    names=[
        "stationID",
        "hour"
    ]
).to_frame(index=False)
full_grid.shape

(304182, 2)

In [56]:
acn_final = (
    full_grid
    .merge(
        acn_hourly,
        on=[
            "stationID",
            "hour"
        ],
        how="left"
    )
)

In [57]:
acn_final["hour_of_day"] = (
    acn_final["hour"]
    .dt.hour
)

acn_final["day_of_week"] = (
    acn_final["hour"]
    .dt.dayofweek
)

acn_final["is_weekend"] = (
    acn_final["day_of_week"] >= 5
).astype(int)

acn_final["month"] = (
    acn_final["hour"]
    .dt.month
)

In [58]:
acn_final["region"] = "Caltech"

acn_final["data_source"] = "ACN"

In [59]:
acn_final.head()

,stationID,hour,demand_kwh,num_sessions,avg_session_kwh,avg_connected_hours,avg_charging_hours,price,revenue,hour_of_day,day_of_week,is_weekend,month,region,data_source
0,2-39-123-23,2018-04-25 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,2,0,4,Caltech,ACN
1,2-39-123-23,2018-04-25 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,2,0,4,Caltech,ACN
2,2-39-123-23,2018-04-25 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2,0,4,Caltech,ACN
3,2-39-123-23,2018-04-25 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,2,0,4,Caltech,ACN
4,2-39-123-23,2018-04-25 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,2,0,4,Caltech,ACN

In [60]:
acn_final.isna().sum()

stationID                   0
hour                        0
demand_kwh             289311
num_sessions           289311
avg_session_kwh        289311
avg_connected_hours    289311
avg_charging_hours     289311
price                  289311
revenue                289311
hour_of_day                 0
day_of_week                 0
is_weekend                  0
month                       0
region                      0
data_source                 0
dtype: int64

In [61]:
acn_final.shape

(304182, 15)

In [62]:
acn_final["demand_kwh"].describe()

count    14871.000000
mean         9.076260
std          7.053923
min          0.501000
25%          4.103000
50%          7.521000
75%         13.209500
max         69.373000
Name: demand_kwh, dtype: float64

In [63]:
zero_cols = [
    "demand_kwh",
    "num_sessions",
    "avg_session_kwh",
    "avg_connected_hours",
    "avg_charging_hours",
    "price",
    "revenue"
]

acn_final[zero_cols] = (
    acn_final[zero_cols]
    .fillna(0)
)

In [64]:
acn_final.isna().sum()

stationID              0
hour                   0
demand_kwh             0
num_sessions           0
avg_session_kwh        0
avg_connected_hours    0
avg_charging_hours     0
price                  0
revenue                0
hour_of_day            0
day_of_week            0
is_weekend             0
month                  0
region                 0
data_source            0
dtype: int64

In [65]:
acn.to_csv('acn_cleaned_hour_grid',index=False)

# UrbanEV Preprocessing

In [66]:
volume_cols = set(volume.columns)
occupancy_cols = set(occupancy.columns)
price_cols = set(price.columns)
duration_cols = set(duration.columns)

print(
    volume_cols == occupancy_cols
)

print(
    volume_cols == price_cols
)

print(
    volume_cols == duration_cols
)
print(volume.shape)
print(occupancy.shape)
print(price.shape)
print(duration.shape)

True
True
True
(8640, 248)
(8640, 248)
(8640, 248)
(8640, 248)

In [67]:
station_cols = [
    c
    for c in volume.columns
    if c != "timestamp"
]
station_cols[1:5]
len(station_cols)

247

In [68]:
volume.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,2022-06-19 00:00:00,2.858333,5.907222,6.478889,5.145,2.286667,3.048889,5.526111,0.381111,0.762222,3.811111,2.286667,1.905556,1.143333,2.667778,1.905556,1.143333,2.286667,6.478889,9.337222,6.288333,1.905556,2.096111,7.622222,5.335556,15.435000,2.286667,0.381111,23.030000,1.524444,4.001667,5.934444,1.905556,11.814444,28.011667,3.048889,8.003333,16.197222,159.358889,30.298333,0.381111,0.0,8.057778,0.381111,28.474444,1.143333,4.954444,9.337222,11.623889,10.671111,5.145,34.681111,61.522222,16.877778,25.915556,9.337222,25.725000,15.816111,4.954444,8.003333,7.241111,352.527778,2.667778,49.816667,5.335556,1.524444,18.483889,20.008333,38.383333,3.43,604.333333,1.905556,1.524444,19.6,16.333333,0.0,1.524444,4.192222,430.220000,8.166667,0.0,0.762222,3.43,0.0,3.43,0.381111,177.543333,3.048889,251.914444,9.908889,46.168889,1.333889,14.373333,7.622222,0.381111,0.762222,25.915556,20.961111,3.92,3.239444,167.743333,4.382778,4.573333,1.905556,9.582222,40.833333,46.795000,1.524444,14.101111,3.43,14.210000,39.581111,30.107778,39.200000,0.762222,0.0,2.667778,155.166667,7.241111,18.674444,8.384444,4.763889,18.293333,196.0,3.048889,0.381111,8.765556,1.715,26.786667,17.15,6.097778,36.695556,1.143333,182.497778,0.381111,14.482222,0.0,2.477222,26.677778,1.715,23.264111,73.554444,2.286667,1.905556,7.622222,20.961111,0.0,45.733333,0.762222,71.866667,1.715,0.762222,0.381111,74.153333,6.097778,4.573333,0.381111,31.060556,34.109444,2.286667,7.241111,11.814444,32.775556,2.286667,1.524444,4.573333,0.381111,17.150000,0.0,6.669444,11.814444,1.333889,23.438333,129.223889,16.197222,20.198889,26.868333,9.527778,188.976667,45.733333,27.140556,0.0,2.667778,6.097778,51.45,0.762222,9.337222,3.048889,3.239444,5.716667,17.748889,10.861667,0.381111,5.335556,2.286667,14.482222,1.905556,0.0,8.003333,5.907222,0.762222,23.383889,0.762222,0.571667,0.0,4.192222,4.382778,31.033333,0.762222,4.573333,0.762222,5.716667,1.715,0.571667,1.143333,0.190556,1.524444,1.905556,4.573333,2.286667,0.0,1.524444,3.811111,4.573333,5.907222,1.524444,105.676667,1.905556,357.808889,2.286667,202.315556,0.762222,0.0,2.858333,4.192222,0.762222,0.0,11.433333,0.0,2.286667,0.381111,12.195556,8.956111,240.236111,5.335556,0.381111,2.286667,2.096111
1,2022-06-19 00:05:00,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,11.666667,8.166667,23.625000,3.500000,0.583333,35.250000,2.333333,6.125000,9.083333,2.916667,18.083333,42.875000,5.069167,12.250000,24.791667,243.916667,46.375000,0.583333,0.0,12.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.333333,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,39.375000,24.208333,7.583333,12.250000,11.083333,539.583333,4.083333,76.250000,8.166667,2.333333,28.291667,30.625000,58.750000,5.25,925.000000,2.916667,2.333333,30.0,25.000000,0.0,2.333333,6.416667,658.500000,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,271.750000,4.666667,385.583333,15.166667,70.666667,2.041667,22.000000,11.666667,0.583333,1.166667,39.666667,32.083333,6.00,4.958333,256.750000,6.708333,7.000000,2.916667,14.666667,62.500000,71.625000,2.333333,21.583333,5.25,21.750000,60.583333,46.083333,60.000000,1.166667,0.0,4.083333,237.500000,11.083333,28.583333,12.833333,7.291667,28.000000,300.0,4.666667,0.583333,13.416667,2.625,41.000000,26.25,9.333333,56.166667,1.750000,279.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,35.608333,112.583333,3.500000,2.916667,11.666667,32.083333,0.0,70.000000,1.166667,110.000000,2.625,1.166667,0.583333,113.500000,9.333333,7.000000,0.583333,47.541667,52.208333,3.500000,11.083333,18.083333,50.166667,3.500000,2.333333,7.000000,0.583333,26.250000,0.0,10.208333,18.083333,2.041667,35.875000,197.791667,24.791667,30.916667,41.125000,14.583333,289.250000,70.000000,41.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,16.625000,0.583333,8.166667,3.500000,22.166667,2.916667,0.0,12.250000,9.041667,1.166667,35.791667,1.166667,0.875000,0.0,6.416667,6.708333,47.500000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,9.041667,2.333333,161.750000,2.916667,547.666667,3.500000,309.666667,1.166667,0.0,4.375000,6.416667,1.166667,0.0,17.500000,0.0,3.500000,0.583333,18.666667,13.708333,367.708333,8.166667,0.583333,3.500000,3.208333
2,2022-06-19 00:10:00,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,11.666667,8.166667,23.625000,3.500000,0.583333,63.252500,2.333333,6.125000,9.083333,2.916667,18.083333,43.277500,5.250000,12.250000,24.791667,243.916667,46.375000,0.583333,0.0,198.633333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.333333,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,39.375000,24.208333,7.583333,12.250000,11.083333,539.583333,4.083333,76.250000,8.166667,2.333333,28.291667,30.625000,58.750000,5.25,925.000000,2.916667,2.333333,30.0,25.000000,0.0,2.333333,6.416667,658.500000,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,271.750000,4.666667,385.583333,15.166667,70.666667,2.041667,22.000000,11.666667,0.583333,1.166667,39.666667,32.083333,6.00,4.958333,256.750000,6.708333,7.000000,2.916667,14.666667,62.500000,71.625000,2.333333,21.583333,5.25,21.750000,60.583333,46.083333,60.000000,1.166667,0.0,4.083333,237.500000,11.083333,28.583333,12.833333,7.291667,28.000000,300.0,4.666667,0.583333,13.416667,2.625,41.000000,26.25,9.333333,56.166667,1.750000,279.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,35.608333,112.583333,3.500000,2.916667,11.666667,32.485833,0.0,70.000000,1.166667,110.000000,2.625,1.166667,0.583333,154.900000,9.333333,7.000000,0.583333,47.541667,52.208333,3.500000,11.083333,18.083333,50.166667,3.500000,2.333333,7.000000,0.583333,26.250000,0.0,10.208333,18.083333,2.041667,35.875000,197.791667,24.791667,30.916667,41.125000,14.583333,289.250000,70.000000,41.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,16.625000,0.583333,8.166667,3.500000,22.166667,2.916667,0.0,12.250000,9.041667,1.166667,35.791667,1.166667,0.875000,0.0,6.416667,6.708333,52.330000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.639167,2.333333,161.750000,2.916667,676.466667,3.500000,309.666667,1.166667,0.0,4.375000,6.416667,1.166667,0.0,17.500000,0.0,3.500000,0.583333,18.666667,13.708333,367.708333,8.166667,0.583333,3.500000,3.208333
3,2022-06-19 00:15:00,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,12.071111,8.166667,24.029444,3.904444,0.583333,75.833333,2.333333,6.125000,9.083333,3.321111,18.487778,43.053889,5.250000,12.250000,24.387222,278.583333,45.566111,0.583333,0.0,282.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.737778,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,40.183889,24.208333,7.583333,12.250000,11.083333,570.783333,4.083333,85.494444,8.166667,2.333333,31.758333,30.625000,58.750000,5.25,990.866667,6.383333,2.333333,40.4,25.000000,0.0,2.333333,6.416667,732.455556,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,306.416667,4.666667,486.116667,15.166667,70.666667,2.041667,32.400000,11.666667,0.583333,1.166667,39.666667,31.274444,6.00,4.958333,287.950000,6.708333,7.000000,2.916667,11.200000,62.500000,80.291667,2.333333,21.583333,5.25,14.816667,67.516667,46.083333,87.733333,1.166667,0.0,4.083333,248.708889,11.083333,28.583333,12.833333,7.696111,28.000000,300.0,5.071111,0.583333,15.034444,2.625,41.000000,26.25,8.928889,56.166667,1.750000,300.133333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,36.012778,132.574444,3.500000,2.916667,11.666667,32.666667,0.0,97.733333,0.762222,207.066667,2.625,1.166667,0.583333,173.500000,9.333333,7.000000,0.583333,47.946111,53.826111,3.500000,11.083333,18.487778,50.571111,3.500000,2.333333,7.404444,0.583333,27.058889,0.0,10.208333,18.892222,2.041667,35.875000,232.458333,24.791667,30.916667,41.125000,14.583333,361.761111,76.933333,48.475000,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,17.433889,0.583333,8.166667,3.500000,22.571111,2.916667,0.0,12.250000,9.446111,1.166667,35.993889,1.166667,0.875000,0.0,6.416667,6.708333,54.500000,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.458333,2.333333,203.350000,2.916667,734.333333,3.500000,384.026667,1.166667,0.0,4.375000,6.821111,1.166667,0.0,17.095556,0.0,3.500000,0.583333,18.666667,13.708333,426.641667,8.166667,0.583333,3.500000,3.208333
4,2022-06-19 00:20:00,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,5.833333,3.500000,2.916667,1.750000,4.083333,2.916667,1.750000,3.500000,9.916667,14.291667,9.625000,2.916667,3.208333,12.250000,8.166667,24.208333,4.083333,0.583333,75.434722,2.333333,6.125000,9.083333,3.500000,18.666667,42.875000,5.250000,12.250000,24.208333,293.916667,45.208333,0.583333,0.0,282.333333,0.583333,43.583333,1.750000,7.583333,14.291667,17.791667,16.916667,7.875,53.083333,94.166667,25.833333,39.666667,14.291667,40.541667,24.208333,7.583333,12.250000,11.083333,584.583333,4.083333,89.583333,8.166667,2.731944,33.291667,30.625000,58.750000,5.25,1020.000000,7.916667,2.333333,45.0,25.000000,0.0,2.333333,6.416667,765.166667,12.500000,0.0,1.166667,5.25,0.0,5.25,0.583333,321.750000,4.666667,530.583333,15.166667,70.666667,2.041667,37.000000,11.666667,0.583333,1.166667,39.666667,30.916667,6.00,4.958333,301.750000,6.708333,7.000000,2.916667,9.666667,62.500000,84.125000,2.333333,21.583333,5.25,11.750000,70.583333,46.083333,100.000000,1.166667,0.0,4.083333,253.666667,11.083333,28.583333,12.833333,7.875000,28.000000,300.0,5.250000,0.583333,15.750000,2.625,41.000000,26.25,8.750000,56.166667,1.750000,309.333333,0.583333,22.166667,0.0,3.791667,40.833333,2.625,36.191667,141.416667,3.500000,2.916667,11.666667,33.065278,0.0,110.000000,0.583333,250.000000,2.625,1.166667,0.583333,194.000000,9.333333,7.000000,0.583333,48.125000,54.541667,3.500000,11.083333,18.666667,50.750000,3.500000,2.333333,7.583333,0.583333,27.416667,0.0,10.208333,19.250000,2.041667,35.875000,247.791667,24.791667,30.916667,41.125000,14.583333,393.833333,80.000000,51.541667,0.0,4.083333,9.333333,78.75,1.166667,14.291667,4.666667,4.958333,8.750000,27.166667,17.791667,0.583333,8.166667,3.500000,22.750000,2.916667,0.0,12.250000,9.625000,1.166667,36.083333,1.166667,0.875000,0.0,6.416667,6.708333,59.283333,1.166667,7.000000,1.166667,8.750000,2.625,0.875000,1.750000,0.291667,2.333333,2.916667,7.000000,3.500000,0.0,2.333333,5.833333,7.000000,8.458333,2.333333,221.750000,2.916667,770.777778,3.500000,416.916667,1.166667,0.0,4.375000,7.000000,1.166667,0.0,16.916667,0.0,3.500000,0.583333,18.666667,13.708333,452.708333,8.166667,0.583333,3.500000,3.208333

## melting cols

In [69]:
# melting volume
volume_long = volume.melt(
    id_vars="timestamp",
    var_name="stationID",
    value_name="volume_kwh"
)
volume_long.shape

(2134080, 3)

In [70]:
print(volume_long.dtypes)

timestamp     datetime64[ns]
stationID             object
volume_kwh           float64
dtype: object

In [71]:
volume_long['volume_kwh'].nunique()

106498

In [72]:
print(volume_long.head())

            timestamp stationID  volume_kwh
0 2022-06-19 00:00:00       102    2.858333
1 2022-06-19 00:05:00       102    4.375000
2 2022-06-19 00:10:00       102    4.375000
3 2022-06-19 00:15:00       102    4.375000
4 2022-06-19 00:20:00       102    4.375000

In [73]:
# occupnacy col
occupancy_long = occupancy.melt(
    id_vars="timestamp",
    var_name="stationID",
    value_name="occupancy"
)

In [74]:
#duration
duration_long = duration.melt(
    id_vars="timestamp",
    var_name="stationID",
    value_name="duration_hours"
)

In [75]:
# price
price_long = price.melt(
    id_vars="timestamp",
    var_name="stationID",
    value_name="price"
)

In [76]:
print(volume_long.shape)
print(occupancy_long.shape)
print(duration_long.shape)
print(price_long.shape)

(2134080, 3)
(2134080, 3)
(2134080, 3)
(2134080, 3)

In [77]:
print(volume_long.dtypes)
print(occupancy_long.dtypes)
print(duration_long.dtypes)
print(price_long.dtypes)

timestamp     datetime64[ns]
stationID             object
volume_kwh           float64
dtype: object
timestamp    datetime64[ns]
stationID            object
occupancy             int64
dtype: object
timestamp         datetime64[ns]
stationID                 object
duration_hours           float64
dtype: object
timestamp    datetime64[ns]
stationID            object
price               float64
dtype: object

## merging

In [78]:
# merging occupancy with volume
urban_long = (
    volume_long
    .merge(
        occupancy_long,
        on=[
            "timestamp",
            "stationID"
        ],
        how="inner"
    )
)
urban_long.shape

(2134080, 4)

In [79]:
# mergeing duration
urban_long = (
    urban_long
    .merge(
        duration_long,
        on=[
            "timestamp",
            "stationID"
        ],
        how="inner"
    )
)

In [80]:
urban_long = (
    urban_long
    .merge(
        price_long,
        on=[
            "timestamp",
            "stationID"
        ],
        how="inner"
    )
)

In [81]:
display(urban_long.head())
urban_long.shape

            timestamp stationID  volume_kwh  occupancy  duration_hours  price
0 2022-06-19 00:00:00       102    2.858333         12            0.49  0.924
1 2022-06-19 00:05:00       102    4.375000         12            0.75  0.924
2 2022-06-19 00:10:00       102    4.375000         12            0.75  0.924
3 2022-06-19 00:15:00       102    4.375000         12            0.75  0.924
4 2022-06-19 00:20:00       102    4.375000         12            0.75  0.924

(2134080, 6)

## woks on other columns

In [82]:
print(stations.shape)
print(information.shape)

display(stations.head())
display(information.head())

(1706, 6)
(247, 10)

   station_id   latitude   longitude  fast  slow  count
0           1  22.716272  113.826349     5     5     10
1           2  22.678851  114.049721    20     0     20
2           3  22.509541  114.058510     0     8      8
3           4  22.605970  114.122110     0     6      6
4           5  22.732771  113.816951     0    55     55

,num,grid,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,1,102,30,3,27,0.71,114.1030,22.54041,0,0
1,3,105,93,0,93,0.77,114.1208,22.55127,0,0
2,5,107,88,2,86,0.89,114.1304,22.54486,0,0
3,6,108,39,0,39,1.26,114.1315,22.55403,0,0
4,7,109,39,0,39,3.15,114.1430,22.56388,0,0

In [83]:
print(stations.columns.tolist())
print(information.columns.tolist())

['station_id', 'latitude', 'longitude', 'fast', 'slow', 'count']
['num', 'grid', 'count', 'fast_count', 'slow_count', 'area', 'lon', 'la', 'CBD', 'dynamic_pricing']

In [84]:
print(
    stations["station_id"].nunique()
)
print(
    urban_long["stationID"].nunique()
)
urban_ids = set(
    urban_long["stationID"].astype(str)
)

station_ids = set(
    stations["station_id"].astype(str)
)

print(
    len(
        urban_ids.intersection(
            station_ids
        )
    )
)

1706
247
247

In [85]:
station_id=stations['station_id'].tolist()
ustation_id=urban_long['stationID'].tolist()
print(station_id[0:10])
print(ustation_id[0:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['102', '102', '102', '102', '102', '102', '102', '102', '102', '102']

In [86]:
#rename station id to grid
urban_long = urban_long.rename(
    columns={
        "stationID": "grid"
    }
)

In [87]:
urban_long["grid"] = (
    urban_long["grid"]
    .astype(int)
)

In [88]:
#merging information csv
urban_long = urban_long.merge(
    information,
    on="grid",
    how="left"
)
urban_long.head()

,timestamp,grid,volume_kwh,occupancy,duration_hours,price,num,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,2022-06-19 00:00:00,102,2.858333,12,0.49,0.924,1,30,3,27,0.71,114.103,22.54041,0,0
1,2022-06-19 00:05:00,102,4.375000,12,0.75,0.924,1,30,3,27,0.71,114.103,22.54041,0,0
2,2022-06-19 00:10:00,102,4.375000,12,0.75,0.924,1,30,3,27,0.71,114.103,22.54041,0,0
3,2022-06-19 00:15:00,102,4.375000,12,0.75,0.924,1,30,3,27,0.71,114.103,22.54041,0,0
4,2022-06-19 00:20:00,102,4.375000,12,0.75,0.924,1,30,3,27,0.71,114.103,22.54041,0,0

<!-- # fast_count	charger capacity
# slow_count	charger mix
# count	total chargers
# area	density proxy
# lon	location
# la	location
# CBD	business district indicator
# dynamic_pricing	existing pricing policy -->

In [89]:
# fast_count	charger capacity
# slow_count	charger mix
# count	total chargers
# area	density proxy
# lon	location
# la	location
# CBD	business district indicator
# dynamic_pricing	existing pricing policy

In [90]:
urban_long[
    [
        "volume_kwh",
        "occupancy",
        "duration_hours",
        "price"
    ]
].describe()

         volume_kwh     occupancy  duration_hours         price
count  2.134080e+06  2.134080e+06    2.134080e+06  2.134080e+06
mean   3.667845e+01  2.190204e+01    1.472631e+00  9.585707e-01
std    1.018935e+02  2.479975e+01    1.803075e+00  1.812571e-01
min    0.000000e+00  0.000000e+00    0.000000e+00  2.500000e-01
25%    2.333333e+00  5.000000e+00    3.333333e-01  8.495900e-01
50%    7.000000e+00  1.300000e+01    8.333333e-01  9.837500e-01
75%    2.333333e+01  3.000000e+01    1.862222e+00  1.072640e+00
max    1.492500e+03  2.200000e+02    1.708333e+01  1.470000e+00

In [91]:
duration.head()

,timestamp,102,105,107,108,109,110,111,115,123,124,202,204,205,206,208,215,216,217,223,224,225,226,227,235,307,309,320,322,323,324,325,326,328,329,330,331,332,333,335,340,343,346,347,348,406,408,501,502,506,512,513,519,520,522,525,526,527,529,552,570,576,577,580,584,585,587,588,589,594,595,596,598,627,628,630,631,632,633,636,638,643,644,655,656,681,682,686,690,691,693,698,699,700,701,702,703,704,705,706,708,709,710,711,712,715,716,719,724,728,729,732,733,735,737,739,741,744,745,746,751,771,773,775,781,783,784,790,795,799,802,804,831,832,835,842,848,849,851,852,855,858,862,883,887,888,890,891,893,895,897,900,901,902,903,904,937,965,966,967,969,972,974,975,979,982,983,986,987,988,989,991,996,998,1000,1009,1011,1015,1026,1029,1031,1032,1037,1043,1049,1060,1061,1062,1066,1067,1068,1071,1072,1074,1075,1076,1081,1082,1083,1085,1086,1088,1090,1092,1093,1095,1096,1098,1099,1100,1101,1102,1104,1105,1106,1107,1109,1110,1111,1112,1113,1114,1115,1119,1121,1122,1124,1126,1131,1134,1137,1138,1143,1144,1149,1154,1156,1159,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,2022-06-19 00:00:00,0.49,0.871111,0.98,0.762222,0.326667,0.381111,0.98,0.054444,0.108889,0.544444,0.326667,0.272222,0.163333,0.381111,0.272222,0.163333,0.326667,0.925556,2.232222,0.98,0.272222,0.435556,1.088889,0.762222,2.504444,0.435556,0.054444,0.653333,0.217778,0.598889,0.435556,0.326667,1.851111,3.920000,0.435556,1.143333,2.504444,1.633333,4.464444,0.108889,0.0,0.272222,0.054444,1.197778,0.217778,0.707778,1.633333,1.197778,1.524444,0.925556,4.954444,2.123333,0.762222,3.702222,1.633333,3.756667,1.96,0.707778,1.143333,1.034444,3.702222,0.326667,0.326667,0.762222,0.217778,2.722222,2.94,1.197778,0.49,4.083333,0.272222,0.217778,0.326667,0.108889,0.0,0.217778,0.598889,4.518889,0.054444,0.0,0.108889,0.49,0.0,0.49,0.054444,1.633333,0.435556,2.014444,1.415556,1.034444,0.217778,0.816667,1.143333,0.054444,0.108889,3.702222,3.212222,0.381111,0.653333,1.088889,0.653333,0.707778,0.272222,0.544444,0.272222,3.538889,0.217778,2.395556,0.272222,0.272222,0.381111,4.301111,0.381111,0.108889,0.0,0.381111,2.940000,1.034444,2.667778,1.197778,0.762222,1.306667,0.816667,0.435556,0.054444,1.252222,0.326667,3.375556,2.177778,0.871111,0.435556,0.163333,2.341111,0.054444,2.068889,0.0,0.381111,4.954444,0.272222,3.756667,4.410000,0.326667,0.272222,1.088889,2.994444,0.0,0.490000,0.108889,0.598889,0.272222,0.108889,0.054444,0.925556,0.925556,0.653333,0.054444,4.028889,4.736667,0.326667,1.034444,1.687778,4.682222,0.326667,0.217778,0.653333,0.054444,2.450000,0.0,1.143333,1.796667,0.217778,3.375556,2.722222,3.157778,3.157778,4.246667,1.361111,2.286667,0.381111,2.885556,0.0,0.381111,1.143333,6.805556,0.108889,1.361111,0.435556,0.544444,0.816667,2.341111,1.687778,0.108889,0.762222,0.326667,2.450000,0.272222,0.0,1.143333,0.980000,0.108889,1.470000,0.108889,0.163333,0.0,0.598889,0.653333,0.653333,0.108889,0.653333,0.108889,0.816667,0.272222,0.108889,0.163333,0.054444,0.217778,0.272222,0.653333,0.326667,0.0,0.217778,0.544444,0.653333,0.871111,0.217778,1.034444,0.326667,2.068889,0.326667,3.321111,0.108889,0.0,0.435556,0.598889,0.108889,0.0,1.905556,0.0,0.326667,0.054444,1.905556,1.306667,8.493333,0.544444,0.054444,0.435556,0.326667
1,2022-06-19 00:05:00,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.666667,1.166667,3.833333,0.666667,0.083333,1.000000,0.333333,0.916667,0.666667,0.500000,2.833333,6.000000,0.724167,1.750000,3.833333,2.500000,6.833333,0.166667,0.0,0.416667,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.333333,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.750000,3.00,1.083333,1.750000,1.583333,5.666667,0.500000,0.500000,1.166667,0.333333,4.166667,4.50,1.833333,0.75,6.250000,0.416667,0.333333,0.500000,0.166667,0.0,0.333333,0.916667,6.916667,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.500000,0.666667,3.083333,2.166667,1.583333,0.333333,1.250000,1.750000,0.083333,0.166667,5.666667,4.916667,0.583333,1.000000,1.666667,1.000000,1.083333,0.416667,0.833333,0.416667,5.416667,0.333333,3.666667,0.416667,0.416667,0.583333,6.583333,0.583333,0.166667,0.0,0.583333,4.500000,1.583333,4.083333,1.833333,1.166667,2.000000,1.250000,0.666667,0.083333,1.916667,0.500000,5.166667,3.333333,1.333333,0.666667,0.250000,3.583333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.750000,6.750000,0.500000,0.416667,1.666667,4.583333,0.0,0.750000,0.166667,0.916667,0.416667,0.166667,0.083333,1.416667,1.416667,1.000000,0.083333,6.166667,7.250000,0.500000,1.583333,2.583333,7.166667,0.500000,0.333333,1.000000,0.083333,3.750000,0.0,1.750000,2.750000,0.333333,5.166667,4.166667,4.833333,4.833333,6.500000,2.083333,3.500000,0.583333,4.416667,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.583333,0.166667,1.166667,0.500000,3.750000,0.416667,0.0,1.750000,1.500000,0.166667,2.250000,0.166667,0.250000,0.0,0.916667,1.000000,1.000000,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.333333,0.333333,1.583333,0.500000,3.166667,0.500000,5.083333,0.166667,0.0,0.666667,0.916667,0.166667,0.0,2.916667,0.0,0.500000,0.083333,2.916667,2.000000,13.000000,0.833333,0.083333,0.666667,0.500000
2,2022-06-19 00:10:00,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.666667,1.166667,3.833333,0.666667,0.083333,1.287500,0.333333,0.916667,0.666667,0.500000,2.833333,6.057500,0.750000,1.750000,3.833333,2.500000,6.833333,0.166667,0.0,1.336667,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.333333,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.750000,3.00,1.083333,1.750000,1.583333,5.666667,0.500000,0.500000,1.166667,0.333333,4.166667,4.50,1.833333,0.75,6.250000,0.416667,0.333333,0.500000,0.166667,0.0,0.333333,0.916667,6.916667,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.500000,0.666667,3.083333,2.166667,1.583333,0.333333,1.250000,1.750000,0.083333,0.166667,5.666667,4.916667,0.583333,1.000000,1.666667,1.000000,1.083333,0.416667,0.833333,0.416667,5.416667,0.333333,3.666667,0.416667,0.416667,0.583333,6.583333,0.583333,0.166667,0.0,0.583333,4.500000,1.583333,4.083333,1.833333,1.166667,2.000000,1.250000,0.666667,0.083333,1.916667,0.500000,5.166667,3.333333,1.333333,0.666667,0.250000,3.583333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.750000,6.750000,0.500000,0.416667,1.666667,4.640833,0.0,0.750000,0.166667,0.916667,0.416667,0.166667,0.083333,1.761667,1.416667,1.000000,0.083333,6.166667,7.250000,0.500000,1.583333,2.583333,7.166667,0.500000,0.333333,1.000000,0.083333,3.750000,0.0,1.750000,2.750000,0.333333,5.166667,4.166667,4.833333,4.833333,6.500000,2.083333,3.500000,0.583333,4.416667,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.583333,0.166667,1.166667,0.500000,3.750000,0.416667,0.0,1.750000,1.500000,0.166667,2.250000,0.166667,0.250000,0.0,0.916667,1.000000,1.057500,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.275833,0.333333,1.583333,0.500000,3.914167,0.500000,5.083333,0.166667,0.0,0.666667,0.916667,0.166667,0.0,2.916667,0.0,0.500000,0.083333,2.916667,2.000000,13.000000,0.833333,0.083333,0.666667,0.500000
3,2022-06-19 00:15:00,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.724444,1.166667,3.891111,0.724444,0.083333,1.416667,0.333333,0.916667,0.666667,0.557778,2.891111,6.025556,0.750000,1.750000,3.775556,2.731111,6.717778,0.166667,0.0,1.750000,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.391111,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.865556,3.00,1.083333,1.750000,1.583333,5.897778,0.500000,0.557778,1.166667,0.333333,4.224444,4.50,1.833333,0.75,6.712222,0.474444,0.333333,0.673333,0.166667,0.0,0.333333,0.916667,7.494444,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.788889,0.666667,3.834444,2.166667,1.583333,0.333333,1.365556,1.750000,0.083333,0.166667,5.666667,4.801111,0.583333,1.000000,1.840000,1.000000,1.083333,0.416667,0.775556,0.416667,5.474444,0.333333,3.666667,0.416667,0.358889,0.641111,6.583333,0.814444,0.166667,0.0,0.583333,4.788889,1.583333,4.083333,1.833333,1.224444,2.000000,1.250000,0.724444,0.083333,2.147778,0.500000,5.166667,3.333333,1.275556,0.666667,0.250000,3.756667,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.807778,6.807778,0.500000,0.416667,1.666667,4.666667,0.0,0.981111,0.108889,1.378889,0.416667,0.166667,0.083333,1.916667,1.416667,1.000000,0.083333,6.224444,7.423333,0.500000,1.583333,2.641111,7.224444,0.500000,0.333333,1.057778,0.083333,3.865556,0.0,1.750000,2.865556,0.333333,5.166667,4.455556,4.833333,4.833333,6.500000,2.083333,3.904444,0.641111,4.474444,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.698889,0.166667,1.166667,0.500000,3.807778,0.416667,0.0,1.750000,1.557778,0.166667,2.307778,0.166667,0.250000,0.0,0.916667,1.000000,1.083333,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.250000,0.333333,1.930000,0.500000,4.250000,0.500000,5.892222,0.166667,0.0,0.666667,0.974444,0.166667,0.0,2.858889,0.0,0.500000,0.083333,2.916667,2.000000,13.288889,0.833333,0.083333,0.666667,0.500000
4,2022-06-19 00:20:00,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,0.833333,0.500000,0.416667,0.250000,0.583333,0.416667,0.250000,0.500000,1.416667,3.416667,1.50,0.416667,0.666667,1.750000,1.166667,3.916667,0.750000,0.083333,1.359722,0.333333,0.916667,0.666667,0.583333,2.916667,6.000000,0.750000,1.750000,3.750000,2.833333,6.666667,0.166667,0.0,1.750000,0.083333,1.833333,0.333333,1.083333,2.500000,1.833333,2.416667,1.416667,7.583333,3.250000,1.166667,5.666667,2.500000,5.916667,3.00,1.083333,1.750000,1.583333,6.000000,0.500000,0.583333,1.166667,0.390278,4.250000,4.50,1.833333,0.75,6.916667,0.500000,0.333333,0.750000,0.166667,0.0,0.333333,0.916667,7.750000,0.083333,0.0,0.166667,0.75,0.0,0.75,0.083333,2.916667,0.666667,4.166667,2.166667,1.583333,0.333333,1.416667,1.750000,0.083333,0.166667,5.666667,4.750000,0.583333,1.000000,1.916667,1.000000,1.083333,0.416667,0.750000,0.416667,5.500000,0.333333,3.666667,0.416667,0.333333,0.666667,6.583333,0.916667,0.166667,0.0,0.583333,4.916667,1.583333,4.083333,1.833333,1.250000,2.000000,1.250000,0.750000,0.083333,2.250000,0.500000,5.166667,3.333333,1.250000,0.666667,0.250000,3.833333,0.083333,3.166667,0.0,0.583333,7.583333,0.416667,5.833333,6.833333,0.500000,0.416667,1.666667,4.723611,0.0,1.083333,0.083333,1.583333,0.416667,0.166667,0.083333,2.087500,1.416667,1.000000,0.083333,6.250000,7.500000,0.500000,1.583333,2.666667,7.250000,0.500000,0.333333,1.083333,0.083333,3.916667,0.0,1.750000,2.916667,0.333333,5.166667,4.583333,4.833333,4.833333,6.500000,2.083333,4.083333,0.666667,4.500000,0.0,0.583333,1.750000,10.416667,0.166667,2.083333,0.666667,0.833333,1.250000,3.583333,2.750000,0.166667,1.166667,0.500000,3.833333,0.416667,0.0,1.750000,1.583333,0.166667,2.333333,0.166667,0.250000,0.0,0.916667,1.000000,1.140278,0.166667,1.000000,0.166667,1.250000,0.416667,0.166667,0.250000,0.083333,0.333333,0.416667,1.000000,0.500000,0.0,0.333333,0.833333,1.000000,1.250000,0.333333,2.083333,0.500000,4.477778,0.500000,6.250000,0.166667,0.0,0.666667,1.000000,0.166667,0.0,2.833333,0.0,0.500000,0.083333,2.916667,2.000000,13.416667,0.833333,0.083333,0.666667,0.500000

In [92]:
urban_long["hour"] = (
    urban_long["timestamp"]
    .dt.floor("h")
)
urban_long[
    [
        "timestamp",
        "hour"
    ]
].head()

            timestamp       hour
0 2022-06-19 00:00:00 2022-06-19
1 2022-06-19 00:05:00 2022-06-19
2 2022-06-19 00:10:00 2022-06-19
3 2022-06-19 00:15:00 2022-06-19
4 2022-06-19 00:20:00 2022-06-19

## created urban_hourly data

In [93]:
urban_hourly = (
    urban_long
    .groupby(
        [
            "grid",
            "hour"
        ]
    )
    .agg(
        demand_kwh=(
            "volume_kwh",
            "sum"
        ),

        avg_occupancy=(
            "occupancy",
            "mean"
        ),

        avg_duration_hours=(
            "duration_hours",
            "mean"
        ),

        avg_price=(
            "price",
            "mean"
        ),

        charger_count=(
            "count",
            "first"
        ),

        fast_count=(
            "fast_count",
            "first"
        ),

        slow_count=(
            "slow_count",
            "first"
        ),

        area=(
            "area",
            "first"
        ),

        lon=(
            "lon",
            "first"
        ),

        la=(
            "la",
            "first"
        ),

        CBD=(
            "CBD",
            "first"
        ),

        dynamic_pricing=(
            "dynamic_pricing",
            "first"
        )
    )
    .reset_index()
)

In [94]:
urban_hourly["revenue"] = (
    urban_hourly["demand_kwh"]
    *
    urban_hourly["avg_price"]
)

In [95]:
urban_hourly["utilization_rate"] = (
    urban_hourly["avg_occupancy"]
    /
    urban_hourly["charger_count"]
)

In [96]:
urban_hourly['utilization_rate'].describe()

count    177840.000000
mean          0.280248
std           0.174459
min           0.000000
25%           0.151927
50%           0.250000
75%           0.376984
max           1.076923
Name: utilization_rate, dtype: float64

In [97]:
urban_hourly["utilization_rate"] = (
    urban_hourly["utilization_rate"]
    .clip(
        lower=0,
        upper=1
    )
)

In [98]:
urban_hourly["hour_of_day"] = (
    urban_hourly["hour"]
    .dt.hour
)

urban_hourly["day_of_week"] = (
    urban_hourly["hour"]
    .dt.dayofweek
)

urban_hourly["is_weekend"] = (
    urban_hourly["day_of_week"]
    >= 5
).astype(int)

urban_hourly["month"] = (
    urban_hourly["hour"]
    .dt.month
)

In [99]:
urban_hourly[
    [
        "demand_kwh",
        "utilization_rate",
        "revenue"
    ]
].describe()

          demand_kwh  utilization_rate        revenue
count  177840.000000     177840.000000  177840.000000
mean      440.141374          0.280242     359.986468
std      1213.589588          0.174434     871.016981
min         0.000000          0.000000       0.000000
25%        28.000000          0.151927      27.545000
50%        84.000000          0.250000      81.830000
75%       282.019062          0.376984     262.628604
max     17439.004167          1.000000   10976.642462

In [100]:
urban_hourly.head()

,grid,hour,demand_kwh,avg_occupancy,avg_duration_hours,avg_price,charger_count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing,revenue,utilization_rate,hour_of_day,day_of_week,is_weekend,month
0,102,2022-06-19 00:00:00,50.983333,12.0,0.728333,0.924,30,3,27,0.71,114.103,22.54041,0,0,47.1086,0.4,0,6,1,6
1,102,2022-06-19 01:00:00,52.500000,12.0,0.750000,0.924,30,3,27,0.71,114.103,22.54041,0,0,48.5100,0.4,1,6,1,6
2,102,2022-06-19 02:00:00,52.500000,12.0,0.750000,0.924,30,3,27,0.71,114.103,22.54041,0,0,48.5100,0.4,2,6,1,6
3,102,2022-06-19 03:00:00,52.500000,12.0,0.750000,0.924,30,3,27,0.71,114.103,22.54041,0,0,48.5100,0.4,3,6,1,6
4,102,2022-06-19 04:00:00,52.500000,12.0,0.750000,0.924,30,3,27,0.71,114.103,22.54041,0,0,48.5100,0.4,4,6,1,6

In [101]:
urban_hourly["hour"].head(20)

0    2022-06-19 00:00:00
1    2022-06-19 01:00:00
2    2022-06-19 02:00:00
3    2022-06-19 03:00:00
4    2022-06-19 04:00:00
5    2022-06-19 05:00:00
6    2022-06-19 06:00:00
7    2022-06-19 07:00:00
8    2022-06-19 08:00:00
9    2022-06-19 09:00:00
10   2022-06-19 10:00:00
11   2022-06-19 11:00:00
12   2022-06-19 12:00:00
13   2022-06-19 13:00:00
14   2022-06-19 14:00:00
15   2022-06-19 15:00:00
16   2022-06-19 16:00:00
17   2022-06-19 17:00:00
18   2022-06-19 18:00:00
19   2022-06-19 19:00:00
Name: hour, dtype: datetime64[ns]

# Merging the dataset

## standardize

In [102]:
acn_final = acn_final.rename(
    columns={
        "stationID": "entity_id"
    }
)

In [103]:
acn_final["entity_type"] = "station"

In [104]:
urban_hourly = urban_hourly.rename(
    columns={
        "grid": "entity_id"
    }
)
urban_hourly["entity_type"] = "grid"

In [105]:
acn_final.describe()

,hour,demand_kwh,num_sessions,avg_session_kwh,avg_connected_hours,avg_charging_hours,price,revenue,hour_of_day,day_of_week,is_weekend,month
count,304182,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000,304182.000000
mean,2018-08-20 19:00:00,0.443725,0.049244,0.441978,0.290777,0.159042,0.733327,6.655870,11.505592,3.012604,0.286171,8.155512
min,2018-04-25 11:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
25%,2018-06-23 03:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,0.000000,6.000000
50%,2018-08-20 19:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,3.000000,0.000000,8.000000
75%,2018-10-18 11:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,5.000000,1.000000,10.000000
max,2018-12-16 03:00:00,69.373000,4.000000,69.373000,245.269167,104.428333,15.000000,1040.595000,23.000000,6.000000,1.000000,12.000000
std,NaN,2.502581,0.218087,2.494840,1.917135,0.993752,3.234529,37.538715,6.924320,1.991647,0.451971,2.241890

In [106]:
# adding missing column to acn
acn_final["charger_count"] = np.nan
acn_final["fast_count"] = np.nan
acn_final["slow_count"] = np.nan
acn_final["CBD"] = np.nan
acn_final["dynamic_pricing"] = np.nan

In [107]:
urban_hourly["num_sessions"] = np.nan

urban_hourly["avg_session_kwh"] = np.nan

urban_hourly["avg_connected_hours"] = np.nan

urban_hourly["avg_charging_hours"] = np.nan

In [108]:
urban_hourly = urban_hourly.rename(
    columns={
        "avg_price": "price"
    }
)

In [109]:
acn_final["utilization_rate"] = np.nan

In [110]:
urban_hourly["region"] = "Shenzhen"

urban_hourly["data_source"] = "UrbanEV"

In [111]:
set(acn_final.columns) - set(urban_hourly.columns)

set()

In [112]:
set(urban_hourly.columns) - set(acn_final.columns)

{'area', 'avg_duration_hours', 'avg_occupancy', 'la', 'lon'}

In [113]:
common_cols = [
    "entity_id",
    "hour",

    "demand_kwh",
    "price",
    "revenue",

    "hour_of_day",
    "day_of_week",
    "is_weekend",
    "month",

    "region",
    "data_source"
]

In [114]:
acn_common = (
    acn_final[
        common_cols
    ]
    .copy()
)

In [115]:
urban_common = (
    urban_hourly[
        common_cols
    ]
    .copy()
)

In [116]:
cleaned_data = pd.concat(
    [
        acn_common,
        urban_common
    ],
    ignore_index=True
)

In [117]:
cleaned_data.shape

(482022, 11)

## saving datafiles

In [118]:
acn_final.to_csv(
    "acn_station_hour.csv",
    index=False
)

In [119]:
urban_hourly.to_csv(
    "urban_grid_hour.csv",
    index=False
)

In [120]:
cleaned_data.to_csv(
    "cleaned_data.csv",
    index=False
)

In [121]:
print(acn_final.shape)
print(urban_hourly.shape)
print(cleaned_data.shape)
cleaned_data.head()

(304182, 22)
(177840, 27)
(482022, 11)

,entity_id,hour,demand_kwh,price,revenue,hour_of_day,day_of_week,is_weekend,month,region,data_source
0,2-39-123-23,2018-04-25 11:00:00,0.0,0.0,0.0,11,2,0,4,Caltech,ACN
1,2-39-123-23,2018-04-25 12:00:00,0.0,0.0,0.0,12,2,0,4,Caltech,ACN
2,2-39-123-23,2018-04-25 13:00:00,0.0,0.0,0.0,13,2,0,4,Caltech,ACN
3,2-39-123-23,2018-04-25 14:00:00,0.0,0.0,0.0,14,2,0,4,Caltech,ACN
4,2-39-123-23,2018-04-25 15:00:00,0.0,0.0,0.0,15,2,0,4,Caltech,ACN

In [122]:
acn_final.columns

Index(['entity_id', 'hour', 'demand_kwh', 'num_sessions', 'avg_session_kwh',
       'avg_connected_hours', 'avg_charging_hours', 'price', 'revenue',
       'hour_of_day', 'day_of_week', 'is_weekend', 'month', 'region',
       'data_source', 'entity_type', 'charger_count', 'fast_count',
       'slow_count', 'CBD', 'dynamic_pricing', 'utilization_rate'],
      dtype='object')

In [123]:
urban_hourly.columns

Index(['entity_id', 'hour', 'demand_kwh', 'avg_occupancy',
       'avg_duration_hours', 'price', 'charger_count', 'fast_count',
       'slow_count', 'area', 'lon', 'la', 'CBD', 'dynamic_pricing', 'revenue',
       'utilization_rate', 'hour_of_day', 'day_of_week', 'is_weekend', 'month',
       'entity_type', 'num_sessions', 'avg_session_kwh', 'avg_connected_hours',
       'avg_charging_hours', 'region', 'data_source'],
      dtype='object')